### ISSUE TITLE
Вопрос по storage.interface.ts

### ISSUE THREAD

**Issue by aamanunin** [Fafnur/barinb#2]
https://github.com/Fafnur/barinb/blob/28c24ef9d567bfcaf873414e6e748a8f825c53fb/src/app/core/storage/interfaces/storage.interface.ts#L53

В storage имеется два state, один хранится в this.state другой отдается в state$: ReplaySubject. Не лучше ли использовать в этом случае BehaviorSubject, тогда this.state можно убрать?

**Comment by Fafnur** [comment]
State нужен для того, чтобы обновлять состояние, без его получения. Условно прилетело новое значение в storage, делается мерж текущего состояния и нового. BehaviorSubject позволит установить лишь начальное состояние, и при этом будет диспачить всю цепочку событий при подписке на него, но этого делать не нужно (т.е. 3 раза записали значения в storage, потом подписались на state и получили 3 последовательных изменения state, хотя нужно одно последенее).

**Comment by aamanunin** [comment]
Мне кажется BehaviorSubject работает немного не так. При подписке он отдает только текущее значение https://indepth.dev/reference/rxjs/subjects/behavior-subject вот здесь хорошая диаграмма, там как раз добавляется новый подписчик. Что касается обновления, без его получения, то вместо this.state можно использовать this.stateSubject.getValue() и тогда состояние будет только в одном сабжекте. Или сделать функцию this.getState() которая будет вызывать getValue()

Ещё есть один недостаток, что readonly state$ = new ReplaySubject<Record<string, any>>(1); не является приватным, и код снаружи может вызывать .next, для этого обычно делают private subject, а наружу отдаются публичный observable сузив тип.

Сделаю PR с этими доработками? Обсудим по коду?

**Comment by Fafnur** [comment]
Разница в BehaviorSubject и ReplaySubject(1) в том, что новый подписчик получит значение только тогда, когда оно будет доступно. BehaviorSubject всегда вернет значение, в частности null и поэтому иногда стоит делать проверку на NULL если в этом есть потребность.
Если есть желание, можно переписать на BehaviorSubject

**Comment by aamanunin** [comment]
Надо было мне оставить на доработку) Вроде неплохо получилось.
